// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Footer: typeof import('./components/layout/footer/Footer.vue')['default']
    Header: typeof import('./components/layout/header/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Menu: typeof import('./components/layout/menu/Menu.vue')['default']
    PlayList: typeof import('./components/layout/playList/PlayList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
